<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign</name>
   <tag></tag>
   <elementGuidId>79f926ab-b0b3-473f-abc1-e9fe85ce0603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f82449fa-bd2e-40ca-adb3-fe16fc46bd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38df93da-ad4a-43d2-b600-17053ef96ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-sm</value>
      <webElementGuid>32cc9cc7-3684-4b68-a3e9-facd2e7884af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign </value>
      <webElementGuid>3316b598-c141-4c4d-9f46-0ecfa79886da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/app-eworkbag-crr-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-1 ng-star-inserted&quot;]/app-crr-form-renderer-sections-container[1]/div[@class=&quot;mt-1 ml-3 mr-3 h-100&quot;]/app-crr-form-renderer-section[@class=&quot;crr-form-renderer-section-1188-0 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@id=&quot;section-collapse-0&quot;]/ul[@class=&quot;list-group list-group-flush ng-star-inserted&quot;]/li[@class=&quot;list-group-item crr-form-renderer-section-1188-0-field-0 ng-star-inserted&quot;]/app-crr-form-renderer-section-field[1]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-1&quot;]/app-crr-form-renderer-section-field-signature-container[1]/div[@class=&quot;mt-2 ng-star-inserted&quot;]/div[@class=&quot;row mb-1 ng-star-inserted&quot;]/div[@class=&quot;col-md-3 text-right ng-star-inserted&quot;]/button[@class=&quot;btn btn-success btn-sm&quot;]</value>
      <webElementGuid>817b8e3f-a286-4aa0-b47f-18c9fb5b3a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>8e6db43a-2833-4d66-800f-97ba963605da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-collapse-0']/ul/li/app-crr-form-renderer-section-field/div/div/div/app-crr-form-renderer-section-field-signature-container/div/div/div[2]/button</value>
      <webElementGuid>c714014f-0c49-4b78-905b-0afeb758b08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non AC Holder'])[1]/following::button[1]</value>
      <webElementGuid>49c54ea0-dc1b-495c-a9e6-a3f655a8786e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not applicable'])[1]/following::button[1]</value>
      <webElementGuid>f3ea8ea8-e61b-4f9a-8bfe-576a98d22199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AC Holder'])[1]/preceding::button[1]</value>
      <webElementGuid>a1f86b62-6599-4897-a330-d9dc4301bfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::button[1]</value>
      <webElementGuid>b9815bf6-7781-40bc-b209-65e76d3bd315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign']/parent::*</value>
      <webElementGuid>809383ff-b264-4dbc-80e9-a84d076e3d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>f6b8cad9-6327-4fc8-8c8e-2ad8f3211c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sign ' or . = 'Sign ')]</value>
      <webElementGuid>e5e0f3c5-2a40-4222-b1af-b11a08fbb9db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
