<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SST</name>
   <tag></tag>
   <elementGuidId>7c7e2318-e146-4ead-9b79-3688a83f1e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adfaa2137200-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adfaa2137200-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ee30375-6900-4160-92a0-51111a6db51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>bf78e4fd-0c38-4a7f-9b4e-09189875201a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3761fa97-aedc-4626-9cd7-c820d8029159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5cfbb3e-b78e-4dec-8992-4fbffaaca9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adfaa2137200-0</value>
      <webElementGuid>9d6f9576-2d31-45fe-993f-6fba264232a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SST </value>
      <webElementGuid>0db5e518-2b48-4a0c-b10b-ff642528803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adfaa2137200-0&quot;)</value>
      <webElementGuid>daa982f1-5f6d-424b-9df8-d64966729543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='adfaa2137200-0']</value>
      <webElementGuid>7ce150ca-3521-453f-8d68-0f6d5186d5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='adfaa2137200']/div/div[2]/div</value>
      <webElementGuid>9fcc62e6-df4f-4245-92fa-39759e045e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select maintenance workscope'])[1]/following::div[5]</value>
      <webElementGuid>1ac722fd-2c44-44e1-bc3e-396e2aa25d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Task'])[1]/following::div[8]</value>
      <webElementGuid>fffec170-910d-4ca3-b62a-0d64ea36b5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REP'])[1]/preceding::div[1]</value>
      <webElementGuid>0bdb25e8-c906-4187-aa0a-78e67be90011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O/H'])[1]/preceding::div[2]</value>
      <webElementGuid>b017bad1-5fc2-4838-a7e3-8e7bf4c95034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SST']/parent::*</value>
      <webElementGuid>5e6f46e7-6b79-493d-be67-0ec8d6009473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>37ed70a8-1658-4e8a-b9cf-debdee3af605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'adfaa2137200-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>d2340a09-ea88-4965-a6df-9d74cfe47e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af7cedbdd1a4-0']</value>
      <webElementGuid>e6324c6c-eb45-4405-be0a-87ba581bf6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af7cedbdd1a4']/div/div[2]/div</value>
      <webElementGuid>7ade2e40-f07c-423f-bd7f-e9c077652dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af7cedbdd1a4-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>534d790e-43e8-4d5a-9e48-8aaade1a6682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
