<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SST_ng-input</name>
   <tag></tag>
   <elementGuidId>2fc26213-e174-4de0-9abb-06308d9748f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='File Attachments'])[1]/following::div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ngx-spinner-overlay.ng-tns-c33-1.ng-trigger.ng-trigger-fadeIn.ng-star-inserted.ng-animating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc098902-f6ac-40e2-a651-c8f0158a4785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>38cd2e77-dd8b-48bc-ab4a-cc150c9a81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9f9da51f-f80a-4dd2-9174-b42abe978a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ngx-spinner-overlay ng-tns-c33-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating</value>
      <webElementGuid>8a8240eb-9af9-4742-a953-4c701e41e5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8db3ea26-7984-46f7-889c-9efb4ead2eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a4a859c25bbb</value>
      <webElementGuid>ebc78254-ad37-403e-a52a-ebcbb2412c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/ngx-spinner[@class=&quot;ng-tns-c33-1 ng-star-inserted&quot;]/div[@class=&quot;ngx-spinner-overlay ng-tns-c33-1 ng-trigger ng-trigger-fadeIn ng-star-inserted ng-animating&quot;]</value>
      <webElementGuid>8f831874-e161-4730-be75-fb30a969e4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Attachments'])[1]/following::div[2]</value>
      <webElementGuid>ba4ec071-ce9a-4199-8801-ed2c5fff479d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add File'])[3]/following::div[5]</value>
      <webElementGuid>7ce10675-1f8b-4d2d-87fd-528cead12cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-spinner/div</value>
      <webElementGuid>535699db-8808-491d-843c-791586548cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select manual ref'])[1]/following::div[1]</value>
      <webElementGuid>47abb3e4-a913-495d-8432-3f98bce82368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Reference'])[2]/following::div[6]</value>
      <webElementGuid>f443553c-0cc1-411b-ba3c-e51d86285e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Reference'])[1]/preceding::div[5]</value>
      <webElementGuid>7668fb17-c7e0-44fe-a912-f24a590329f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[7]</value>
      <webElementGuid>43979d58-9322-4977-a859-7fea08564905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div/div[2]</value>
      <webElementGuid>855a3eb6-c398-49a4-a0bf-3795e529926e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SST'])[2]/following::div[1]</value>
      <webElementGuid>bd24cf67-3e1a-43fa-af3a-bb9dfba3b8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select work done work scope'])[1]/following::div[2]</value>
      <webElementGuid>1b487ad8-c37d-4d1d-8d04-d6c0673d575d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SST'])[3]/preceding::div[2]</value>
      <webElementGuid>1b3c0dd3-c113-495f-a47e-4f6730829092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REP'])[1]/preceding::div[3]</value>
      <webElementGuid>dec0895f-5f4f-46d3-9b5f-977043232bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div/div/div[3]</value>
      <webElementGuid>f203429d-d29a-415f-9c0d-ca763aca4a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
