<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Job Details Work Stages Defect Rectific_9e6fcf</name>
   <tag></tag>
   <elementGuidId>dddcae3f-9ab5-4300-bb1f-7d6e5ffcda7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Reference'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1bd43ce-3cca-4540-9641-15be59df430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ng-star-inserted</value>
      <webElementGuid>1f834428-eefe-419f-94b9-06465ae110fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24Amended by WSby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - In Progress  Set reference  Add Defect Rectification  Complete  Cancel 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer's Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD</value>
      <webElementGuid>27adac3d-cd65-4172-b6f6-6085460bb646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/wc-job-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-1 ng-star-inserted&quot;]/div[@class=&quot;mt-0 ml-3 mr-3&quot;]/div[@class=&quot;card shadow-sm&quot;]/div[@class=&quot;card-body p-2 pl-4&quot;]/div[@class=&quot;row ng-star-inserted&quot;]</value>
      <webElementGuid>ef23a65c-1dda-4953-a954-638e41e115f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Reference'])[1]/following::div[1]</value>
      <webElementGuid>de2c2208-752b-42e4-b52a-863384fcb3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N. S. N.'])[1]/following::div[2]</value>
      <webElementGuid>5c6118f0-e3c0-4e6b-952d-1631ea9e6994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]</value>
      <webElementGuid>fb30ca1e-ad54-41d9-b695-56ac0cb97da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24Amended by WSby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - In Progress  Set reference  Add Defect Rectification  Complete  Cancel 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;) or . = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24Amended by WSby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - In Progress  Set reference  Add Defect Rectification  Complete  Cancel 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;))]</value>
      <webElementGuid>329421c6-175b-4bf9-84c4-cb2fb431e1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24Amended by WSby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - Not Started  Start  Not Applicable 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;) or . = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24Amended by WSby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - Not Started  Start  Not Applicable 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;))]</value>
      <webElementGuid>5994a858-9744-4944-b8b8-05b237d6ff58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - Not Started  Start  Not Applicable 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;) or . = concat(&quot;Job Details Work Stages Defect Rectification RecordCRR FormsCompliance DeclarationParts Replacement RecordTool TaggingAttachmentsRelated JobsWork StageReferenceStatusAction1. Preliminary Inspection 3834000-45 Completedby EmpNo:80309000 on 12/Dec/24 Approvedby EmpNo:80309000 on 12/Dec/24 Amend 2. Hidden Damage Inspection - Not Started  Start  Not Applicable 3. Pre-disassembly Testing - Not Started  Start  Not Applicable 4. Disassembly - Not Started  Start  Not Applicable 5. Cleaning - Not Started  Start  Not Applicable 6. Inspection/Check - Not Started  Start  Not Applicable 7. Repair - Not Started  Start  Not Applicable 8. Replacement - Not Started  Start  Not Applicable 9. Partial Sub-contract - Not Started  Start  Not Applicable 10. Assembly - Not Started  Start  Not Applicable 11. Painting - Not Started  Start  Not Applicable 12. Testing - Not Started  Start  Not Applicable 13. Final Inspection - Not Started  Start  Not Applicable 14. Duplicate Check - Not Started  Start  Not Applicable 15. Independent Check - Not Started  Start  Not Applicable 16. Loose Article Check - Not Started  Start  Not Applicable  Add Defect/Work to be Carried OutRectification/Action TakenRemarksAction 1.  Data-data seperti nomor referensi salahCreated from work stage Preliminary Inspection.Created by EmpNo:80309000 on 12/Dec/24 Completed by EmpNo:80309000 on 12/Dec/24 Approved by EmpNo:80309000 on 12/Dec/24  Amend CRR Form TypeForm NameCrr No.Issue No.StatusAction No CRR form added to this job.  Certified that the work recorded in this component repair/overhaul record except as otherwise specified was carried out/accomplished in accordance with the requirements of the following authorities/customers and approved for return to service.
 EASA (EASA.145.0139)  CAA China (F06500251)  CAA Malaysia (FAMO/2017/72)  CAA Nepal (AMO/VAL/12/2005)  CAA Philippines (134-F)  CAA Singapore (AWI/059)  CAA Thailand (36/2529)  CAA Vietnam (VN-232NN/CAAV)  DGCA, India (5-2460/2016-AI(2))  CAA Maldives (MV.145.049)  DGCA, Indonesia (145F-063)  FAA, USA (FW4Y195M)  DCA, Laos (AMO/A-056/21)  PACAF, Pacific Air Forces, USAF  US Navy Requirements  Applicable Manufacturer&quot; , &quot;'&quot; , &quot;s Manual  Applicable Customer’s Requirements  Republic of Singapore Air Force Logistics Orders  SSCA Cambodia (AMO/17/17)  Pakistan PCAA Pakistan (PCAA.145.173)  Declared by EmpNo:80309000 on 12/Dec/24  Undeclare Compliance  Refresh  Declare Materials  Last Refresh on: EmpNo:80309000 12/Dec/24 MaterialMatDescSLIssQtyFinalQtyBatchNo Material12 Material DescriptionSL200046 Material18 Material DescriptionSL140052 Material4 Material DescriptionSL180055FirstPrevious1NextLast Tag Tools  Declare Tool Tagging LocationRef NoSerial NoCal. Report NoCalibrationEquipmentPart NoPart Description Actions  No tools tagged to this job.  Attach File  No attachments found 80000302 - MAIN ROTOR HEAD&quot;))]</value>
      <webElementGuid>43445504-4d8c-47b4-89d2-4b52f613a222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
