<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MOD</name>
   <tag></tag>
   <elementGuidId>a1efbcb5-fcee-4879-a7c7-a94e92bfb4f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ac7c1ea7cef1-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ac7c1ea7cef1-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f07e8f7-2a82-4bb0-867a-04e5b614197e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>b5c6beca-9a51-4e4a-95f8-c431ddd0dbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e4ba17ef-47fe-434f-a4fe-0b38dfe9ebb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e52e451-a2b1-4b76-9093-3ed6e29199c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ac7c1ea7cef1-3</value>
      <webElementGuid>5a7a7f98-46a7-4213-a5f7-6d1ab69eed86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> MOD </value>
      <webElementGuid>c6bd30b6-ac31-401b-83e1-ff53a769ba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac7c1ea7cef1-3&quot;)</value>
      <webElementGuid>4b6e192f-c4ab-4d0b-a1b2-8c5495a38b96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ac7c1ea7cef1-3']</value>
      <webElementGuid>d93d1bb1-0a22-4eda-91de-255d42a879bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ac7c1ea7cef1']/div/div[2]/div[4]</value>
      <webElementGuid>b717f9e6-58ff-42ab-b3e4-e08d9d9207f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O/H'])[1]/following::div[1]</value>
      <webElementGuid>11e3c568-77cc-4872-91d6-a0c2233809af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REP'])[3]/following::div[2]</value>
      <webElementGuid>dd156e3a-3652-47d0-a871-bb399f16a253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial CRR Nos.'])[1]/preceding::div[2]</value>
      <webElementGuid>7f0f283e-40aa-456d-8896-bad8ddc8a482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strtmlfn date'])[1]/preceding::div[3]</value>
      <webElementGuid>330dbadd-b0d3-44a4-829c-8db518e4e881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[4]</value>
      <webElementGuid>1025b684-ee22-433d-a1d0-996738084e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ac7c1ea7cef1-3' and (text() = ' MOD ' or . = ' MOD ')]</value>
      <webElementGuid>a22dc1e0-7104-401e-8d1d-109bc64b65f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
