<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SST</name>
   <tag></tag>
   <elementGuidId>7c7e2318-e146-4ead-9b79-3688a83f1e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a993e4c4e781-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a993e4c4e781-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c78fef9-bf7c-4856-9c49-6372f56d5b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>d767eaa4-987c-48f6-8f7f-bfcaf372e134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>11f30ed7-0ecd-4027-b8ea-764ea5870147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a72bb08-3123-43f1-aa8f-d86e1ef8fec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a993e4c4e781-0</value>
      <webElementGuid>48c4b0f4-6c21-4ba8-8600-c657404db268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SST </value>
      <webElementGuid>dfbd98fb-cbb9-4eeb-afb5-3d162ee50f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a993e4c4e781-0&quot;)</value>
      <webElementGuid>a2087e4b-27a5-4a32-a80a-ad0ca32c9b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a993e4c4e781-0']</value>
      <webElementGuid>e2532408-d500-40ec-9457-4ff3f90b702c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a993e4c4e781']/div/div[2]/div</value>
      <webElementGuid>09616f99-fd01-40a8-ae27-7f7fdf5c6c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select maintenance workscope'])[1]/following::div[5]</value>
      <webElementGuid>afa72b36-9995-4488-9d7c-ae406ceea8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Task'])[1]/following::div[8]</value>
      <webElementGuid>87021a70-1905-42e2-b5d1-41a577179d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REP'])[1]/preceding::div[1]</value>
      <webElementGuid>7ff85945-6033-412d-8d69-436f1017fc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O/H'])[1]/preceding::div[2]</value>
      <webElementGuid>d69aaa9d-19df-4b1f-a5fa-e2e322aae2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SST']/parent::*</value>
      <webElementGuid>426ffada-57ff-49ef-b15d-df980e20a515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>33af9953-2c03-4e77-8ce4-1a31655f4b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a993e4c4e781-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>8463f77b-5c8c-4554-9da0-df751d8cdd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='adfaa2137200-0']</value>
      <webElementGuid>7ce150ca-3521-453f-8d68-0f6d5186d5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='adfaa2137200']/div/div[2]/div</value>
      <webElementGuid>9fcc62e6-df4f-4245-92fa-39759e045e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'adfaa2137200-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>d2340a09-ea88-4965-a6df-9d74cfe47e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af7cedbdd1a4-0']</value>
      <webElementGuid>e6324c6c-eb45-4405-be0a-87ba581bf6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af7cedbdd1a4']/div/div[2]/div</value>
      <webElementGuid>7ade2e40-f07c-423f-bd7f-e9c077652dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af7cedbdd1a4-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>534d790e-43e8-4d5a-9e48-8aaade1a6682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
