<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_REP</name>
   <tag></tag>
   <elementGuidId>2d4d1a6c-26e5-4c60-b558-bc291b06490c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab44484f27ac-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ab44484f27ac-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f18774d3-2250-4b33-af74-5f2dc62a1af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>44fe06cc-a5b0-43b6-90e7-eaedd7eb85ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a7bb11ad-98f3-4d58-a556-04467f82e040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b14669a-558e-40d8-8e31-5ed97a2cea6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab44484f27ac-1</value>
      <webElementGuid>834a8875-cea5-498e-a29d-caf8355bd42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> REP </value>
      <webElementGuid>9a8b59f7-e2a6-4926-8c1c-402b3088a5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab44484f27ac-1&quot;)</value>
      <webElementGuid>84f789e2-e45c-4a57-a8f2-75ae3ce507d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ab44484f27ac-1']</value>
      <webElementGuid>73dddbcc-0755-46be-aab0-4bbfdf957b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ab44484f27ac']/div/div[2]/div[2]</value>
      <webElementGuid>cee8ce9c-149f-40bd-ba29-c8d835d4eccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SST'])[3]/following::div[1]</value>
      <webElementGuid>b46d2506-7d7d-4bca-8574-54b6c2c9f07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SST'])[2]/following::div[6]</value>
      <webElementGuid>a9bab397-8987-4ee9-a385-963f3acf6048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O/H'])[1]/preceding::div[1]</value>
      <webElementGuid>16e34268-f3be-4e60-b672-a8e9516ee013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOD'])[1]/preceding::div[2]</value>
      <webElementGuid>3d8362c7-fc1c-4da0-bf79-302b1a0cbbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REP']/parent::*</value>
      <webElementGuid>b3392687-9944-4731-ab13-63ae6a086d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>f9c5e70c-f896-4e35-8a8f-bbeb3fddce10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ab44484f27ac-1' and (text() = ' REP ' or . = ' REP ')]</value>
      <webElementGuid>e814b27f-0011-4fd9-9f0d-7d43c9d5bf95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
