<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Created_cursor-pointer</name>
   <tag></tag>
   <elementGuidId>f8ba46f3-256a-4438-9de1-89a235a29e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Tap Card Icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16d384a9-155c-475a-9a07-1a160097d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tap Card Icon</value>
      <webElementGuid>92b6d93e-a00a-44bb-a6f3-ad765200faa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/tap-card-icon.png</value>
      <webElementGuid>ef06d867-1866-40ce-8483-c9374857e1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>d422f726-fbcb-4ebc-8b98-614ae1a27b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/app-prompt-for-auth-card[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;text-center&quot;]/img[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>5afcf17f-11c2-4f7a-ba49-93c8777799a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tap Card Icon']</value>
      <webElementGuid>5a80f95d-b526-413f-9523-ac8bfdfc304a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>d7932683-618d-486b-9e94-06b53d4b5d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Tap Card Icon' and @src = 'img/tap-card-icon.png']</value>
      <webElementGuid>9205de47-07cb-4498-bf06-8c5508b53414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>2eda32dd-9218-42bb-9db0-e6782e09443f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
