<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pass-l96oteqgl7</name>
   <tag></tag>
   <elementGuidId>2187e73f-66a1-4bc9-99ed-003080838b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pass-l96oteqgl7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pass-l96oteqgl7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58d2901a-1833-4c68-a6cd-a85693ac7970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6ff94bdb-b23a-4b34-80ae-31b4ff3bda63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Passed</value>
      <webElementGuid>f925c4f1-9f30-4222-8237-5cfd91c1446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2a2088a4-10ce-43f4-871b-82653904b234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pass-l96oteqgl7</value>
      <webElementGuid>5c017b2d-f7cf-43eb-b24c-c8b0ea818c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pass-l96oteqgl7&quot;)</value>
      <webElementGuid>4da2c613-8cbb-4a0e-86b9-8e8fc5d18be0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pass-l96oteqgl7']</value>
      <webElementGuid>4daa5ed2-6a04-443d-9252-add1ac515cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-collapse-0']/ul/li[2]/app-crr-form-renderer-section-field/div/div/div/div[2]/wc-pass-fail-field/div/input</value>
      <webElementGuid>21ef38ff-d160-46df-bf21-f01905d74e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//wc-pass-fail-field/div/input</value>
      <webElementGuid>1d8bfeb2-40b6-4dc3-a50b-bea39aca428d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'pass-l96oteqgl7']</value>
      <webElementGuid>1ac7a13e-076f-44c1-bfbf-318674712b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
