<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_field-notapplicable-1</name>
   <tag></tag>
   <elementGuidId>276d646c-319c-4663-a60e-537d72fb73ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-notapplicable-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-notapplicable-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>530dbaec-0f71-47df-b22f-90502c87b91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>deb60442-d9da-4815-94f1-81d5e375b6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>263b5e52-8b4b-430e-9560-45cb46c1f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-notapplicable-1</value>
      <webElementGuid>908ca7f1-90b4-4672-b6a1-1adb3c0bafb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-notapplicable-1&quot;)</value>
      <webElementGuid>9d5f5568-9a08-4262-b63d-979c1abd2d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-notapplicable-1']</value>
      <webElementGuid>fe18c972-906d-4c8d-a2ea-ed2ba23ff98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-collapse-0']/ul/li[2]/app-crr-form-renderer-section-field/div/div/div/div[3]/input</value>
      <webElementGuid>abd480bb-118d-4f9f-9edb-9f85061bfdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/app-crr-form-renderer-section-field/div/div/div/div[3]/input</value>
      <webElementGuid>b8430b54-5352-4c17-880a-cafd4c965ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'field-notapplicable-1']</value>
      <webElementGuid>9bd24122-6020-40b5-a5f7-0d768338ecb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
