<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Back</name>
   <tag></tag>
   <elementGuidId>2899f773-9e41-4241-9748-9b0ed77a2b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbar-view-mode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar-view-mode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>fa052659-daaa-4765-bdb5-a378f827641e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbar-view-mode</value>
      <webElementGuid>1f936e08-a367-42cf-9ea4-c32426ec6982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar</value>
      <webElementGuid>d075bc8c-fd39-4331-9e82-dfab0d12de0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Back </value>
      <webElementGuid>e8b1dc28-65f8-4e11-9df6-7b7be9e980ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-view-mode&quot;)</value>
      <webElementGuid>2796e03f-8b51-4a98-bc31-efc256873532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//nav[@id='navbar-view-mode']</value>
      <webElementGuid>7d815c60-f78f-4ca2-a0da-1aa1b8186dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Order'])[1]/following::nav[1]</value>
      <webElementGuid>3b79d3da-3d5b-4aa9-895b-c41168b3db33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eWorkbag'])[1]/following::nav[1]</value>
      <webElementGuid>b626f6a0-e3d2-43ed-b210-67ac8860ab5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned Technicians'])[1]/preceding::nav[1]</value>
      <webElementGuid>005a0fc9-aff5-4c91-b3e1-36e4b255bdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>2c5403ff-abb7-42ea-a258-c09765a3a8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[@id = 'navbar-view-mode' and (text() = ' Back ' or . = ' Back ')]</value>
      <webElementGuid>8a017775-7e0e-43bc-99da-afb06eb20733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
