<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SST_fa fa-check fa-lg</name>
   <tag></tag>
   <elementGuidId>84936c16-20af-4a5e-9b6a-c1d5c705bc0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-check.fa-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6b2344a-b909-490e-b738-f6422b7527fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check fa-lg</value>
      <webElementGuid>0a42b935-dfb4-4716-8ecf-0c9f3f13571c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/wc-job-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-1 ng-star-inserted&quot;]/div[@class=&quot;mt-0 ml-3 mr-3&quot;]/div[@class=&quot;card shadow-sm&quot;]/div[@class=&quot;card-body p-2 pl-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-4 mb-3 required&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;click-to-edit-input-button button btn-secondary&quot;]/span[@class=&quot;fa fa-check fa-lg&quot;]</value>
      <webElementGuid>a337047d-3fdd-42ca-bb0d-c3e24061f973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>4358f56b-34cd-42e1-80b4-f0c4ab339791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
