<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_DefectWork to be Carried Out_works_dbf6d0</name>
   <tag></tag>
   <elementGuidId>0f2e57e8-136c-40ea-8de1-61312c9a0b2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='workstage-defect-work-to-be-carried-out']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workstage-defect-work-to-be-carried-out</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>43042daa-3b44-4762-b08e-8e856e261bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b54137e8-210a-4360-b069-eefdb62636a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b93d23cd-30c6-49c7-b99b-6615ad564977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workstage-defect-work-to-be-carried-out</value>
      <webElementGuid>c61b15af-e5fd-4c27-ba8a-b8a37dcda915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a18f69ee-d556-44c0-9d0d-8570bdba96c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-touched ng-dirty</value>
      <webElementGuid>859fcee1-692e-4206-9df5-657c4a9fe4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workstage-defect-work-to-be-carried-out&quot;)</value>
      <webElementGuid>5cc8889d-d7be-424c-a3fa-27e13041694a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='workstage-defect-work-to-be-carried-out']</value>
      <webElementGuid>197ab5f4-06a9-4ed0-902a-69e8fbd3070e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>61c050c2-cc31-4260-990a-cc428c89623b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'workstage-defect-work-to-be-carried-out']</value>
      <webElementGuid>104c56c8-01b8-45e9-b147-29055085d33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
