<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_RS  WS</name>
   <tag></tag>
   <elementGuidId>b4147b76-578f-485b-99f1-c1382929d369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job-role-dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='job-role-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>ab084f1c-f54f-44ac-ac83-4e42399809b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job-role-dropdown</value>
      <webElementGuid>958611c6-0079-40a2-8a8d-9344ec98ff72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>1637aad7-77da-4e4c-87a3-c0783dc0e17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>job-role-button</value>
      <webElementGuid>46945e85-e978-492c-ae9f-94337341dfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu dropdown-menu-right show ng-star-inserted</value>
      <webElementGuid>45594bb2-81de-4a12-85f7-56edb4ec8775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RS  WS </value>
      <webElementGuid>f4bea7b8-1c51-4d99-b913-8c7b4021790f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-role-dropdown&quot;)</value>
      <webElementGuid>332dcfef-2829-4421-b476-3f43ea851c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='job-role-dropdown']</value>
      <webElementGuid>4cbd1108-7275-4be9-8afc-2aff58c2e698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Involved As'])[1]/following::ul[1]</value>
      <webElementGuid>ead0f278-0ed6-4fdf-8dce-e9a1e3bc6301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Started'])[1]/following::ul[1]</value>
      <webElementGuid>d04f86fe-e2bd-409b-8a94-6d2c9d0e50bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul</value>
      <webElementGuid>ac5f9340-8cff-44c3-81b2-55d19da28603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'job-role-dropdown' and (text() = ' RS  WS ' or . = ' RS  WS ')]</value>
      <webElementGuid>fec12f8d-858d-404f-bbd5-1ce694a2f473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
