<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SST</name>
   <tag></tag>
   <elementGuidId>b361b7db-7dec-47ad-881b-79a8a803b94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab5326766e96-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ab5326766e96-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>446b73a4-008c-410a-90fd-97c71ab33968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-option-marked ng-star-inserted</value>
      <webElementGuid>4caf7846-278b-4309-9b33-82d5a01df337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>05f033ab-e5d9-40ee-a81a-6e2f13a0d7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aba85a45-4717-4b6d-b51d-da5f92336de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab5326766e96-0</value>
      <webElementGuid>a01ce316-7798-471e-804e-709ed736d7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SST </value>
      <webElementGuid>00a59c9e-0b8c-41c0-87be-20de1d0402d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab5326766e96-0&quot;)</value>
      <webElementGuid>49ebe072-4e6e-4bea-b9fe-bd4569157733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ab5326766e96-0']</value>
      <webElementGuid>db54b63a-ccc7-49d8-a4e8-e2a3939bc1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ab5326766e96']/div/div[2]/div</value>
      <webElementGuid>4056f9bc-3899-4e85-895c-21d67260c304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SST'])[1]/following::div[5]</value>
      <webElementGuid>528959e7-83b5-47ec-9c30-683a0706fa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select maintenance workscope'])[1]/following::div[6]</value>
      <webElementGuid>767313da-ccf8-4ca2-8482-23c700cdfaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REP'])[1]/preceding::div[1]</value>
      <webElementGuid>5c079d37-6423-4e0d-9c95-b0f7f418200b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O/H'])[1]/preceding::div[2]</value>
      <webElementGuid>b73fe38d-85d9-4f9e-86c2-0d56f1790190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>bf5a3ef1-8a3f-46ba-953b-fc223a16420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ab5326766e96-0' and (text() = ' SST ' or . = ' SST ')]</value>
      <webElementGuid>e722ca96-7fb7-4e60-9651-04db81f9d49b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
