<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RW32-11-10003</name>
   <tag></tag>
   <elementGuidId>46c3fe09-c928-4ca5-9314-dd58f97b9f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngb-typeahead-0-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ngb-typeahead-0-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b16a8d29-f306-461f-b9fc-1c2f8cac750b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>408a726b-f30e-4c0d-b8ed-f6ce30045604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item ng-tns-c92-2 ng-trigger ng-trigger-typeaheadAnimation ng-star-inserted active</value>
      <webElementGuid>c23a22ca-9dad-4188-b4df-f07efdc1ef2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngb-typeahead-0-2</value>
      <webElementGuid>ce2dfedf-3b35-48e7-95c9-4d51a57eaec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RW/32-11-10/003</value>
      <webElementGuid>185120a4-3f85-4ee9-a7e7-77287e568e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-typeahead-0-2&quot;)</value>
      <webElementGuid>dad6fec8-c09b-406f-bd62-2b2ac983afec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ngb-typeahead-0-2']</value>
      <webElementGuid>a4fe15e9-cfbb-4e0a-a320-105dcea6d360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//typeahead-container[@id='ngb-typeahead-0']/button[3]</value>
      <webElementGuid>29af3d52-a774-43cd-a740-771ab9a06876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[2]/following::button[1]</value>
      <webElementGuid>2edac43c-18fd-4528-9a67-69c6baa9abf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//typeahead-container/button[3]</value>
      <webElementGuid>cbb81b2d-3905-42da-a512-de0fc3d58efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ngb-typeahead-0-2' and (text() = 'RW/32-11-10/003' or . = 'RW/32-11-10/003')]</value>
      <webElementGuid>7b5b8917-91c4-43e5-9e54-c0fe2ed59c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
