<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>1dd557c9-22dd-4926-b4b4-562000d0f458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#crr-form-verify-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='crr-form-verify-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d871144-aaee-4204-aa5e-3111bd422ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>crr-form-verify-button</value>
      <webElementGuid>14b905bb-9cb9-4eff-a2dc-ae9a9b203c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33e841a0-aec9-4772-b976-66324c1f5956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-3 ng-star-inserted</value>
      <webElementGuid>df04c788-0850-4f75-bd76-d3a0f4b34c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Verify </value>
      <webElementGuid>078790c4-dbe1-4fe4-8742-ea75b49eefef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crr-form-verify-button&quot;)</value>
      <webElementGuid>7e5c137b-61e4-4044-9673-a5c91767bfa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='crr-form-verify-button']</value>
      <webElementGuid>087b1625-2ad6-496e-9b86-850d0b1e8c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-view-mode']/div/button[2]</value>
      <webElementGuid>5e324ae6-33c2-473b-9b3b-8ec3d33e92e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amend'])[1]/following::button[1]</value>
      <webElementGuid>6f381544-aa50-460e-9236-d12510b52a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::button[2]</value>
      <webElementGuid>92cb98a4-d396-4dbf-90f0-b495d8285aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Router Form Information'])[1]/preceding::button[1]</value>
      <webElementGuid>1a80e952-73d4-4c1f-ab55-456232ede3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job No.'])[1]/preceding::button[1]</value>
      <webElementGuid>53b46ee7-b1de-4e03-a934-aecf37bb1bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify']/parent::*</value>
      <webElementGuid>33b236d2-010d-4a80-ad2f-5b846c594342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>be000733-91d1-44c8-9069-5d0145388bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'crr-form-verify-button' and @type = 'button' and (text() = ' Verify ' or . = ' Verify ')]</value>
      <webElementGuid>bd9f2535-9836-4f80-8474-e67770c2ebc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
