<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign</name>
   <tag></tag>
   <elementGuidId>4a25480c-1dd5-43ad-b9dc-2aad0c60a689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>698a0bbf-00fe-4b9b-98b6-574876f2a446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>294af1bb-75fe-45c5-83ac-ac4c95654c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-sm</value>
      <webElementGuid>aebfeb01-df5e-40ea-96d1-e4841db7f848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign </value>
      <webElementGuid>e4d5a001-e776-4665-8bb9-8af9be9a8a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/app-eworkbag-crr-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pt-1 ng-star-inserted&quot;]/app-crr-form-renderer-sections-container[1]/div[@class=&quot;mt-1 ml-3 mr-3 h-100&quot;]/app-crr-form-renderer-section[@class=&quot;crr-form-renderer-section-761-1 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@id=&quot;section-collapse-1&quot;]/ul[@class=&quot;list-group list-group-flush ng-star-inserted&quot;]/li[@class=&quot;list-group-item crr-form-renderer-section-761-1-field-0 ng-star-inserted&quot;]/app-crr-form-renderer-section-field[1]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;p-1&quot;]/app-crr-form-renderer-section-field-signature-container[1]/div[@class=&quot;mt-2 ng-star-inserted&quot;]/div[@class=&quot;row mb-1 ng-star-inserted&quot;]/div[@class=&quot;col-md-3 text-right ng-star-inserted&quot;]/button[@class=&quot;btn btn-success btn-sm&quot;]</value>
      <webElementGuid>ef6cc64e-d773-462b-9649-e71140ec08b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
      <webElementGuid>38e3f5c1-832e-4ecf-90fb-82f6f2bd054c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-collapse-1']/ul/li/app-crr-form-renderer-section-field/div/div/div/app-crr-form-renderer-section-field-signature-container/div/div[2]/div[2]/button</value>
      <webElementGuid>1b2e3331-dbe5-4169-8378-d266d66ef067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required.'])[1]/following::button[1]</value>
      <webElementGuid>5a5d35f2-57a8-441c-8fc5-16f34af7dc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>b6db6d99-fad8-4cd9-bb19-4548a71c6ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section #2:'])[1]/preceding::button[1]</value>
      <webElementGuid>a4041ec3-e6dc-43ab-aa2c-22264a5a1648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign']/parent::*</value>
      <webElementGuid>2f8148fc-70b2-4693-a9e9-c9b360692f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>b31fde66-f412-42d6-b679-35ff831aec7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Sign ' or . = 'Sign ')]</value>
      <webElementGuid>8082fc1b-3c89-42ed-ae48-e79c608c3dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
