<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MinhTestPart2</name>
   <tag></tag>
   <elementGuidId>b774a31c-6538-45aa-97d2-bcc64a458ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a377d63cbd5d-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a377d63cbd5d-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6907429-70d9-41ee-952e-b0027da84708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>10f46057-6755-4bf3-8fa4-7441f64b705c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6e05ff45-69c4-4ad0-86cd-1f9207494530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3262047-5fb9-4046-96c9-ae4411e287d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a377d63cbd5d-1</value>
      <webElementGuid>6924109c-3d27-47f7-8191-e7c977f5d1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MinhTestPart2</value>
      <webElementGuid>8ac00ff7-c820-4053-8748-5a04cd77473a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a377d63cbd5d-1&quot;)</value>
      <webElementGuid>7dc134d4-cb09-4aff-88f5-9d3210035cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a377d63cbd5d-1']</value>
      <webElementGuid>42c0f34f-abd5-4848-b385-de596179f663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a377d63cbd5d']/div/div[2]/div[2]</value>
      <webElementGuid>6f52ea1c-d860-4ede-a962-39fec6b6814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MinhTestPart1'])[1]/following::div[1]</value>
      <webElementGuid>371208ec-a3ef-4adc-b7c3-6f60cfe667dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Numbers'])[1]/following::div[6]</value>
      <webElementGuid>0275ce64-e5fe-498a-a2ce-5b5547707f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MinhTestPart3'])[1]/preceding::div[1]</value>
      <webElementGuid>f388e650-db58-4004-887f-3502214b2a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>b0cc5c93-89fa-44ae-87e1-8c0c32aba824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a377d63cbd5d-1' and (text() = 'MinhTestPart2' or . = 'MinhTestPart2')]</value>
      <webElementGuid>5c0ddf2b-b8b5-468e-a7f3-8802efb3bddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
