<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b  - Testing b</name>
   <tag></tag>
   <elementGuidId>2376a134-68cb-403e-aaad-31e807e3d368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a1f60ad20a35-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a1f60ad20a35-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>482c606b-0699-4f66-98f5-5c3562de7ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-selected ng-option-marked</value>
      <webElementGuid>0505532f-a650-4512-8598-8b305a1f806e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>807eeeec-ad91-45c2-8c23-39e7981be64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>143477e5-717a-4340-95b9-64bfa4fc63a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a1f60ad20a35-2</value>
      <webElementGuid>a867438d-1a06-4bdc-a805-f5876a23c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> b  - Testing b</value>
      <webElementGuid>40055542-5ef9-4786-8ba1-52c71b73c515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a1f60ad20a35-2&quot;)</value>
      <webElementGuid>ae6dd023-5512-4c72-899f-67c041a57fb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a1f60ad20a35-2']</value>
      <webElementGuid>c0c0454a-082b-43e7-9a44-24eda1d8c845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a1f60ad20a35']/div/div[2]/div[3]</value>
      <webElementGuid>7e55f082-1b50-4ca8-abcf-938778c9cbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Testing'])[1]/following::div[1]</value>
      <webElementGuid>f03fea47-100c-44ea-a7dd-4bcb6ab4e2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job No.'])[1]/preceding::div[1]</value>
      <webElementGuid>14423068-6e47-4366-9ac2-879b00029544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[3]</value>
      <webElementGuid>eaca58ba-5932-4e01-a40e-f81c1d221b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a1f60ad20a35-2' and (text() = ' b  - Testing b' or . = ' b  - Testing b')]</value>
      <webElementGuid>4c1906d5-3b36-474d-bf2c-12b88c5205ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
