<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Index Page</name>
   <tag></tag>
   <elementGuidId>8abcc22b-6bd8-488a-99c8-f7dabacd31bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aa745d26d893-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aa745d26d893-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a0eb904-01c8-4065-83eb-5b4e720d237c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>5229b48f-85f5-467e-97c3-be66fef52b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7fe35a54-5e95-4eb5-bf28-93c4b36556f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d81d811-35c9-49a9-97e4-b1d6f181e2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aa745d26d893-0</value>
      <webElementGuid>32c9046c-0b2f-4a2c-b4d3-a78fb884c57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Index Page </value>
      <webElementGuid>bf20cf61-16a2-497b-8f61-ac24852cf2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa745d26d893-0&quot;)</value>
      <webElementGuid>f815667e-99ed-447b-867e-9fada5696909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aa745d26d893-0']</value>
      <webElementGuid>3ae1612f-b7a0-44d7-8ec2-307f7de1fb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aa745d26d893']/div/div[2]/div</value>
      <webElementGuid>d5a3dbdc-1398-4bc8-9299-3d9293274d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Index'])[1]/following::div[5]</value>
      <webElementGuid>484d4cd0-6a29-4851-b1e6-b15dfaac79d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Index'])[1]/following::div[8]</value>
      <webElementGuid>c9d53daf-66af-4b34-af63-845eeda7dc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Cadmium Plating'])[1]/preceding::div[1]</value>
      <webElementGuid>71f527cc-64af-4071-8231-7b4ace39a647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Index Page']/parent::*</value>
      <webElementGuid>97b78ae8-4598-4fc1-8fdd-7e77ed328f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>3801d0ab-67e2-4561-bd6a-a7eee867fee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aa745d26d893-0' and (text() = ' Index Page ' or . = ' Index Page ')]</value>
      <webElementGuid>a8b6c27f-2d22-4ad6-b5f7-e02fc2d8bc73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
