<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Success  Rework Worksheet RW32-11-10002_77ae3d</name>
   <tag></tag>
   <elementGuidId>52526159-4f07-45f7-83fc-cca78f9c8c0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c72-3.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d34ac860-567f-4e5e-9f72-2e9c20f6d0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c72-3 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success</value>
      <webElementGuid>553d0f72-78c2-4dba-aecd-47aeb18dc0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>× Success  Rework Worksheet RW/32-11-10/002 Index  added into Router. </value>
      <webElementGuid>2f6bfe5d-1889-44d3-a59c-1ba351707b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c72-3 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success&quot;]</value>
      <webElementGuid>b982de35-635e-47d3-903f-586aad919c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>c554dac9-fdb2-4619-87d4-9cb3ea38f101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach File'])[1]/following::div[6]</value>
      <webElementGuid>9c7bf3cd-adec-4911-82fa-2beb5d3493e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div</value>
      <webElementGuid>2de2d637-ee8b-4c00-bf80-d977e90f949c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '× Success  Rework Worksheet RW/32-11-10/002 Index  added into Router. ' or . = '× Success  Rework Worksheet RW/32-11-10/002 Index  added into Router. ')]</value>
      <webElementGuid>8ba5735e-eb82-4cab-a41f-9e47c8b0f52b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
