<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Confirm and Sign Amendment Please place_5b1a23</name>
   <tag></tag>
   <elementGuidId>dfbf86d9-3530-4f12-bc50-cf73fb9e2d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//modal-container/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>489301cb-c3c1-40af-bcb4-455018ce1c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content</value>
      <webElementGuid>56b0d6f0-05cd-406e-a911-06ca7dfa370a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm and Sign Amendment Please place auth card on reader to complete amended changes. Preliminary Inspection. ReferenceReason for Amendment3834000-100Missing Field This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel </value>
      <webElementGuid>6dbfc788-3fd8-400d-b62a-a0523f7758d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]</value>
      <webElementGuid>4988b76c-9b91-40c9-85e6-92cbe5156c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//modal-container/div[2]/div</value>
      <webElementGuid>b37b27f9-62f5-4d7d-a75e-4a56303116be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Confirm and Sign Amendment Please place auth card on reader to complete amended changes. Preliminary Inspection. ReferenceReason for Amendment3834000-100Missing Field This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel ' or . = 'Confirm and Sign Amendment Please place auth card on reader to complete amended changes. Preliminary Inspection. ReferenceReason for Amendment3834000-100Missing Field This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel ')]</value>
      <webElementGuid>98d952f3-be25-4073-b118-28f9404a9fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
