<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MinhTestPart1</name>
   <tag></tag>
   <elementGuidId>7b689aed-22a7-45c2-9216-bcaa638720dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='abfda84f63a7-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abfda84f63a7-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3db38bed-e28a-48fd-9e9a-379abe3e22b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>7bea45c3-84d5-4e64-aac3-a9f0301f8e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>54ad2aa7-6a0f-4d5a-a463-2edc2afc6684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0660e076-6544-48bd-8998-2d8010ba4232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abfda84f63a7-0</value>
      <webElementGuid>0b99ff50-c913-41ac-8054-918d0de31058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MinhTestPart1</value>
      <webElementGuid>b5c675f4-1170-45ef-b209-dfebd4dcef79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abfda84f63a7-0&quot;)</value>
      <webElementGuid>2b4bfa00-6e64-4106-a8e7-a0ba8df5c9cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='abfda84f63a7-0']</value>
      <webElementGuid>4fb4a31b-0f14-4d92-927d-f5c87eed19fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='abfda84f63a7']/div/div[2]/div</value>
      <webElementGuid>c63bd95b-7d5d-4204-89af-4a295844cefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Numbers'])[1]/following::div[5]</value>
      <webElementGuid>f78dc643-9b50-4858-b969-9c7d332e7f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part No.'])[2]/following::div[8]</value>
      <webElementGuid>e4c0c390-af81-400a-86ed-2e090e33622f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MinhTestPart2'])[1]/preceding::div[1]</value>
      <webElementGuid>ae120588-7dbf-416d-a11a-35362f48c98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>90d9823e-924e-4bde-89f5-07b2de5fd195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'abfda84f63a7-0' and (text() = 'MinhTestPart1' or . = 'MinhTestPart1')]</value>
      <webElementGuid>413ebc99-6e98-4960-9b41-94b28c35aa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a3eabadabac9-0']</value>
      <webElementGuid>aefdc596-9704-4ff1-8c6e-e055d9241d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a3eabadabac9']/div/div[2]/div</value>
      <webElementGuid>11a09fe8-e476-4ad9-8472-64e27806cfe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial No.'])[2]/preceding::div[1]</value>
      <webElementGuid>4cea8264-c147-47ed-8796-8e4ccb86d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a3eabadabac9-0' and (text() = 'MinhTestPart1' or . = 'MinhTestPart1')]</value>
      <webElementGuid>4205fc0f-e34b-40f9-a71b-77dcd04fb209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
