<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Part Numbers</name>
   <tag></tag>
   <elementGuidId>ade252ae-a474-422b-9bbc-f95802bfe787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='partnumbers-rwws']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#partnumbers-rwws > div.ng-select-container > div.ng-value-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2fe1e01-c72a-443f-a875-167cd7438377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-value-container</value>
      <webElementGuid>c61db9d2-57f8-4413-9d6e-7117c78cb4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Part Numbers</value>
      <webElementGuid>067d4ed2-e27d-4b18-a4d2-05ea79da5b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnumbers-rwws&quot;)/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]</value>
      <webElementGuid>abfc37d1-7eb0-4b1c-8058-16a22abfdcd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='partnumbers-rwws']/div/div</value>
      <webElementGuid>95976beb-9bc3-426b-bef2-86d63941b1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part No.'])[2]/following::div[2]</value>
      <webElementGuid>3a1df5e2-4467-468d-8d31-18cf61a9e0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job No.'])[1]/following::div[3]</value>
      <webElementGuid>844ae99a-ddfb-44ab-848d-20dfc1adc55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MinhTestPart1'])[1]/preceding::div[4]</value>
      <webElementGuid>aee0fb94-11c7-4eca-9dfd-346176d4aacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ng-select/div/div</value>
      <webElementGuid>6fa42b82-b572-4d1e-8153-31acc3c11c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Part Numbers' or . = 'Part Numbers')]</value>
      <webElementGuid>957b505f-e880-427d-a693-aa78a95b9c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
