<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Revision No_revision-rwws</name>
   <tag></tag>
   <elementGuidId>344f3241-4803-4400-8328-af06f604dd5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#revision-rwws</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='revision-rwws']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>133c6df3-15ca-42d3-944d-9c6816e20735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>revision-rwws</value>
      <webElementGuid>c6db085e-0dc4-4dd6-b1b9-39b79ba50d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f8cade4-ee82-4cd0-b378-f8d2a03020bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Revision Number</value>
      <webElementGuid>935eae55-3910-4e63-bb4c-92a5c7fb8e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>caf2cb53-7207-408e-923f-c53653b38e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;revision-rwws&quot;)</value>
      <webElementGuid>ffac1eaa-1b7a-4735-a38d-65c681493ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='revision-rwws']</value>
      <webElementGuid>dd5c5867-45ee-4236-bfcc-8198f3a01447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>1ab068d6-19fb-4c7c-8d1d-8ace2fab40f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'revision-rwws' and @type = 'text' and @placeholder = 'Revision Number']</value>
      <webElementGuid>c8d8c941-4ea5-47d3-8045-541816c0e2fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
