<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal-container_Rework WorksheetRework Work_36d470</name>
   <tag></tag>
   <elementGuidId>44aa4a67-d30a-4a0f-a4f9-93cf2f42c349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>modal-container.modal.fade.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach File'])[1]/following::modal-container[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>modal-container</value>
      <webElementGuid>5cf67e67-f343-41c6-bb4a-6d4feb1fe503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>3f767db3-a943-4b67-a277-53f965ac5e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a37f31ad-1c34-4bf0-985d-407936bde620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal fade show</value>
      <webElementGuid>47ce713f-c177-4849-b06e-57b19f413030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b575308-ffb4-4fe8-9cb7-4e780a745cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rework Worksheet×Rework Worksheets No.Revision No.IndexChoose Index×b×Job No.Part No.Part Numbers×MinhTestPart1×Serial No.Repair No.Repair ScopeCMMComments Add  Close </value>
      <webElementGuid>a8ddcf99-43b6-4c31-a92d-399e4c452d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]</value>
      <webElementGuid>b9ca23ae-f33e-480b-a2a3-967b482e9bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach File'])[1]/following::modal-container[1]</value>
      <webElementGuid>aba5504b-7513-4d06-af06-90eef14cc63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//modal-container</value>
      <webElementGuid>90b5cc76-7b56-41db-9f17-71250e033542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//modal-container[(text() = 'Rework Worksheet×Rework Worksheets No.Revision No.IndexChoose Index×b×Job No.Part No.Part Numbers×MinhTestPart1×Serial No.Repair No.Repair ScopeCMMComments Add  Close ' or . = 'Rework Worksheet×Rework Worksheets No.Revision No.IndexChoose Index×b×Job No.Part No.Part Numbers×MinhTestPart1×Serial No.Repair No.Repair ScopeCMMComments Add  Close ')]</value>
      <webElementGuid>dddec8c8-6baf-4240-918c-91e0c425a044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
