<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal-container_Sign workscope and CRR sele_d7fd45</name>
   <tag></tag>
   <elementGuidId>004b44b1-bc19-44bf-b05e-e5d6fb2ec64c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>modal-container.modal.fade.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//modal-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>modal-container</value>
      <webElementGuid>2b4c83ff-1b20-4bcf-a970-ee4c6b478f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>48373bb8-e7e5-4e91-89b6-96d2bc1cc89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0421523c-5f1d-4f5d-bafe-1f861d588977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal fade show</value>
      <webElementGuid>a6d820c3-e0db-4ae9-b97f-544011c3b05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e1b28ea-b93b-4a55-b890-f07ad51a86d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign workscope and CRR selection Please place auth card on reader to sign workscope and CRR selection for job order 7801/41/31012963E This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel </value>
      <webElementGuid>e4a2a1f0-e407-44ad-b33b-f0a0b26973eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]</value>
      <webElementGuid>5227ef98-8e9b-4b59-a27b-1dab0de51757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//modal-container</value>
      <webElementGuid>1ed1fdef-134b-41d8-ad7d-f9ebf10076aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//modal-container[(text() = 'Sign workscope and CRR selection Please place auth card on reader to sign workscope and CRR selection for job order 7801/41/31012963E This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel ' or . = 'Sign workscope and CRR selection Please place auth card on reader to sign workscope and CRR selection for job order 7801/41/31012963E This application is in Auth Card Test mode. This module will not connect to the card reader. Click on the image below to simulate reading from the auth card. Cancel ')]</value>
      <webElementGuid>a39346fc-3e80-47bd-b137-c8d3c18c7124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
