<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal-container_Update Reference Update ref_bd7398</name>
   <tag></tag>
   <elementGuidId>599f7556-1668-4bea-8f2d-c90732cb0751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>modal-container.modal.fade.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//modal-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>modal-container</value>
      <webElementGuid>8312df19-86a3-4a2b-a574-69c676597897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>44c386b6-28de-4343-8f8c-dc27ceea32a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>687f325a-8079-487f-9402-11eafbf02c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal fade show</value>
      <webElementGuid>dc53b029-735d-489a-bea9-c0827fdbc6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd5d6d7b-5a28-4604-8fc2-8f156e0bfb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Reference× Update reference under workstage: Pre-disassembly TestingManual ReferenceSelect manual ref×14 (rev: 002, dated: 01 Jun 2021)×Page ReferencePg 33333-Refer to DRR15ds,kdlkfrffrfjfdskfnsdkvnsdkkkk989Page 12Pg 3Pg 30112Ref to page 301SSESReason for Amendment * Typo Error  Missing Field  For Further Elaboration  Redoing of workstep or workstage due to a change in manual  Redoing of workstep or workstage due to a change in workscope  Others  Update  Cancel </value>
      <webElementGuid>b14b8765-40d9-48bc-a437-102a631fdc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app ng-tns-0-0 header-fixed sidebar-lg-show sidebar-fixed modal-open&quot;]/modal-container[@class=&quot;modal fade show&quot;]</value>
      <webElementGuid>07c2a45c-93dd-47d3-9bf7-15e94aec179d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//modal-container</value>
      <webElementGuid>77ad91f4-1f8a-4c23-9823-0a29f69b46f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//modal-container[(text() = 'Update Reference× Update reference under workstage: Pre-disassembly TestingManual ReferenceSelect manual ref×14 (rev: 002, dated: 01 Jun 2021)×Page ReferencePg 33333-Refer to DRR15ds,kdlkfrffrfjfdskfnsdkvnsdkkkk989Page 12Pg 3Pg 30112Ref to page 301SSESReason for Amendment * Typo Error  Missing Field  For Further Elaboration  Redoing of workstep or workstage due to a change in manual  Redoing of workstep or workstage due to a change in workscope  Others  Update  Cancel ' or . = 'Update Reference× Update reference under workstage: Pre-disassembly TestingManual ReferenceSelect manual ref×14 (rev: 002, dated: 01 Jun 2021)×Page ReferencePg 33333-Refer to DRR15ds,kdlkfrffrfjfdskfnsdkvnsdkkkk989Page 12Pg 3Pg 30112Ref to page 301SSESReason for Amendment * Typo Error  Missing Field  For Further Elaboration  Redoing of workstep or workstage due to a change in manual  Redoing of workstep or workstage due to a change in workscope  Others  Update  Cancel ')]</value>
      <webElementGuid>6994caa2-8cff-49ee-b425-5bc7ded04b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
